name: 'Update Kodknuff Translations'
description: 'Update kodknuff translations to the latest version'
inputs:
  packagePath:
    description: 'relative path to package.json'
    required: true
    default: './package.json'
  translationsPath:
    description: 'relative path to the module exporting the translations'
    required: true
    default: './index'
  artifact:
    description: 'The name of the artifact in Kodknuff to update'
    required: true
  os:
    description: '"win" or "unix"'
    default: 'unix'
outputs:
  version:
    description: 'The version of the translations that were published'
runs:
  using: 'node12'
  main: 'dist/index.js'
